base_url = "https://blog.skmgeek.com/"
title = "SKM GEEK's Blog"
description = "Mabuya is a minimal Zola theme for building light and SEO-ready blogs. Put your work front and center with Mabuya as the base of your project."
author = "SKM GEEK"

compile_sass = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
minify_html = true
build_search_index = false
taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
highlight_theme = "visual-studio-dark"
# More syntax highlighting themes: https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting
smart_punctuation = true

[extra]
author = "SKM GEEK"
email = "qestudios17@gmail.com"
github = "https://github.com/QEStudios"
timeformat = "%Y-%m-%d"                 # e.g. June 14, 2021

[[extra.menu]]
name = "Archive"
url = "/"

[[extra.menu]]
name = "Tags"
url = "tags"

[extra.footer]
info = 'Powered by <a href="https://www.getzola.org" target="_blank">Zola</a> and <a href="https://github.com/semanticdata/mabuya">Mabuya</a>.'
